name: Get list subdirectories
description: Return list of subdirectories in the given parent directory

inputs:
  parent_dir:
    description: Parent directory containing subdirectories
    type: string
    required: false
    
outputs:
  dirs:
    value: ${{ steps.step1.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Get subdirectories
      id: step1
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          
          let results = []
          let isDirExist = false;
          try {
            await fs.promises.access("${{ inputs.parent_dir }}");
            isDirExist = true;
          } catch(e){}

          if( isDirExist ) {
            filenames = fs.readdirSync('${{ inputs.parent_dir }}');
            filenames.forEach(file => { 
              if( fs.statSync('${{ inputs.parent_dir }}'+file).isDirectory() ) {
                results.push({
                  "name": file,
                  "full_name": "${{ inputs.parent_dir }}'+file
                });
              }
            });
          }

          return results
