name: Get monorepo lambdas
description: Return list of monorepo lambdas or empty list if not a monorepo
    
outputs:
  dirs:
    value: ${{ steps.step1.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Get subdirectories
      id: step1
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const parent = 'src/lambdas';
          
          let isDirExist = false;
          try {
            await fs.promises.access(parent);
            isDirExist = true;
          } catch(e){}

          let results = [];
          if( isDirExist ) {
            filenames = fs.readdirSync(parent);
            filenames.forEach(file => { 
              if( fs.statSync(parent+file).isDirectory() ) {
                results.push({
                  "name": file
                });
              }
            });
          }

          return results
