name: Get list of monorepo lambdas
description: Return list of monorepo lambdas or empty list if not a monorepo.

outputs:
  lambdas:
    value: ${{ steps.step1.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: get stuff
      id: step1
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const parent = '${{ github.workspace }}/src/lambdas/';
          console.log('here: ${{ github.workspace }}');
          
          let results = []
          let isDirExist = false;
          try {
            await fs.promises.access(parent);
            isDirExist = true;
          } catch(e){}
          
          if( isDirExist ) {
            filenames = fs.readdirSync(parent);
            filenames.forEach(file => { 
              if( fs.statSync(parent+file).isDirectory() ) {
                console.log(file);
                results.push({
                  "name": file
                });
              }
            });
          }
          
          return results;
