name: Get list of monorepo lambdas
description: Return list of monorepo lambdas or empty list if not a monorepo.

outputs:
  lambdas:
    value: ${{ steps.step1.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: get stuff
      id: step1
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          
          let results = []
          let isDirExist = false;
          try {
            await fs.promises.access("src/lambdas/");
            isDirExist = true;
          } catch(e){}
          if( isDirExist ) {
            filenames = fs.readdirSync('src/lambdas/');
            filenames.forEach(file => { 
              if( fs.statSync('src/lambdas/'+file).isDirectory() ) {
                console.log(file);
                results.push({
                  "name": file
                });
              }
            });
          }
          return results;
