name: Get list of monorepo lambdas
description: Return list of monorepo lambdas or empty list if not a monorepo.

outputs:
  lambdas:
    value: ${{ steps.step1.outputs.lambdas }}

runs:
  using: "composite"
  steps: 
    - id: step1
      shell: python
      run: |
        import json
        import sys
        import os

        dir = "src/lambdas"
        count = 0
        lambdas = ""
        if os.path.isdir(dir):
          #  lambdas = [name for name in os.listdir(dir) if os.path.isdir(os.path.join(dir, name))]
          for name in os.listdir(dir):
            if count == 0:
              lambdas = name
            else:
              lambdas = lambdas + "," + name
            count += 1

        outputs_file = os.getenv("GITHUB_OUTPUT")
        with open(outputs_file, "a") as f:
          f.write(f"lambdas=[{lambdas}]")
