name: Get list of monorepo lambdas
description: Return list of monorepo lambdas or empty list if not a monorepo.

outputs:
  lambdas:
    value: ${{ steps.step1.outputs.lambdas }}

runs:
  using: "composite"
  steps: 
    - id: step1
      shell: python
      run: |
        import json
        import sys
        import os

        lambdas = ""
        #dir = "${{ inputs.home_dir }}/src/lambdas"
        dir = "src/lambdas"

        if os.path.isdir(dir):
          #  lambdas = [name for name in os.listdir(dir) if os.path.isdir(os.path.join(dir, name))]
          cnt = 0
          for name in os.listdir(dir):
            if cnt == 0:
              lambdas = name
            else:
              lambdas = lambdas + "," + name
            cnt = cnt + 1

        print(lambdas)
        outputs_file = os.getenv("GITHUB_OUTPUT")
        with open(outputs_file, "a") as f:
          f.write(f"lambdas={lambdas}")
