on: [workflow_call]

permissions:
  actions: read
  id-token: write
  contents: read
  pull-requests: write

jobs:
  audit_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout
      - name: Authenticate with app
        id: app-token
        uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc
        with:
          app_id: '${{ secrets.APP_ID }}'
          private_key: '${{ secrets.APP_KEY }}'
