name: Build

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: false
        type: string
      aws-region:
        description: "AWS Region to build to"
        required: false
        type: string


permissions:
  actions: read
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/
  pull-requests: write
  deployments: write # Required for deployments

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout

      - uses: FloQastInc/.github/.github/actions/get-ssm-parameters@ATLAS-121
        id: ssm
        with:
          parameter-pairs: '/fq6/spride/test1=ARG1,/fq6/spride/test2=ARG2'
          decrypt: 'true'

      - shell: bash
        run: |
          echo 'ARG1 ...'
          echo "${{ env.ARG1 }}"
          echo '------------------------'
          echo 'ARG2 ...'
          echo "${{ env.ARG2 }}"
