name: Build Something

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
  deployments: write

jobs:
  PRCheck:
    uses: stpride/.github/.github/workflows/pr-check.yaml@main
    secrets: inherit
    
  Stuff:
    runs-on: ubuntu-latest
    steps:
      - name: force-check
        uses: stpride/.github/.github/workflows/pr-force-check.yaml@main
      - name: my-stuff
        shell: bash
        run: |
          echo "Hello there!"
          echo "event_name = ${{ github.event_name }}"
          echo "action = ${{ github.event.action }}"
          echo "merged = ${{ github.event.pull_request.merged }}"
